version: '3.1'

services:
  mongo_db:
    image: mongo
    restart: always

  mongo_seed:
    image: mongo
    links:
      - mongo_db
    volumes:
      - ./mongo-seed/init.json:/init.json
    command: ["mongoimport", "--host", "mongo_db", "--db", "mydatabase", "--collection", "users", "--type", "json", "--file", "/init.json", "--jsonArray"]

  server:
    build:
      context: .
      dockerfile: ./DockerfileNodejs
    image: nodejs
    restart: always
    ports:
      - 8000:8000
    environment:
      - MONGODB_URL=mongodb://mongo_db:27017/mydatabase
      - PORT=8000
      - FRONT_URL
    depends_on:
      - mongo_db
    volumes:
      - .:/server
      - /server/node_modules
    command: node server.js
